---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: userlist
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    # Uncomment this and specify a semver pattern to restrict
    # tags automatically deployed by flux
    # fluxcd.io/tag.chart-image: semver:~1
spec:
  releaseName: userlist
  chart:
    git: https://github.com/awaythrow/userlist.git
    ref: main
    path: deploy/charts/sinatra-app
  values:
    fullnameOverride: userlist
    image:
      repository: ghcr.io/awaythrow/userlist
      tag: main
      pullPolicy: IfNotPresent
    database:
      host: postgres-postgresql
      port: 5432
      username: postgres
      name: sinatra-prod
      password:
        secretName: db-creds
        secretKey: postgresql-password
    ingress:
      enabled: false
      annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
      hosts:
        - host: userlist.local
          paths:
            - /
      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local
